# Welcome to SnowGlobe!

SnowGlobe is a program that assists with literature searching, using a technique called snowballing. Snowballing has emerged as the [gold standard](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1283190/) for comprehensive literature reviews. The process of snowballing takes all known relevant papers and searches through their references (which papers they cite) and citations (which papers cite them). Doing this by hand is an extremely time-consuming process, and until now, there was no way to do this process in bulk. SnowGlobe has several time-saving features such as automatic duplicate removal, as well as the ability to track which titles you have already screened so you don't have to screen them multiple times. 

Proceed to the **Prepare Search** Tab to enter the papers you'd like to search (and the papers you have already searched, if applicable).

Demos for [basic searching](https://youtu.be/WQ_rwvMXFdU) and [the running list feature](https://youtu.be/VsNZ1QyaCGo) are available on YouTube.

Please cite us with the following information: 

McWeeny, S., Choe, J., & Norton, E. (2021). SnowGlobe: An Iterative Search Tool for Systematic Reviews and Meta-Analyses. https://doi.org/10.17605/OSF.IO/U25RN

**NOTE: We are temporarily experiencing an outage due to the termination of Microsoft Academic. We are working to have these issues resolved and apologize for the inconvenience. We are hoping to have a DOI-based version up by mid-March. Please reach out by email if you need assistance**