# Welcome to Snowballer!

Snowballer is a program that assists with literature searching, using a technique called snowballing. Snowballing has emerged as the [gold standard](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1283190/) for comprehensive literature reviews. The process of snowballing takes all known relevant papers and searches through their references (which papers they cite) and citations (which papers cite them). Doing this by hand is an extremely time-consuming process, and until now, there was no way to do this process in bulk. Snowballer has several time-saving features such as automatic duplicate removal, as well as tracking which titles you have already screened.

There are a number of ways to use Snowballer, which are detailed below.

1. It is your first search and you have a list of titles, DOIs, or Pubmed IDs from a reference manager and want all forward and backward associated papers
2. It is your first search and you would like to enter titles one by one from within the snowballer.
3. You have used snowballer in the past and you have a list of already screened titles and would like to add more inputs to your search